# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('home_group', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'db_table': 'Student',
                'indexes': [],
            },
        ),
    ]
